CREATE OR REPLACE PROCEDURE APL_USER_DS_MINSHANXIE.sp_load_order_comment()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    -- Truncate the target table before insert
    TRUNCATE TABLE DB_TEAM_ALBERTA_PRECISION_LABORATORIES_DEVELOPERS.APL_USER_DS_MINSHANXIE.TGT_ORDER_COMMENT_TABLE;

    -- Insert fresh data (LIMIT 3 for testing)
    INSERT INTO DB_TEAM_ALBERTA_PRECISION_LABORATORIES_DEVELOPERS.APL_USER_DS_MINSHANXIE.TGT_ORDER_COMMENT_TABLE
    (
        ORDER_PROC_ID,
        COMMENT_LINE,
        ORDERING_COMMENT,
        AUDIT_LINE,
        AUDIT_TRL_USER_ID,
        USER_NAME,
        AUDIT_TRL_TIME,
        AUDIT_TRL_ACTION_C,
        ACTION_NAME
    )
    SELECT 
        op.ORDER_PROC_ID,
        oc.LINE AS COMMENT_LINE,
        oc.ORDERING_COMMENT,
        oa.LINE AS AUDIT_LINE,
        oa.AUDIT_TRL_USER_ID,
        emp.NAME AS USER_NAME,
        oa.AUDIT_TRL_TIME,
        oa.AUDIT_TRL_ACTION_C,
        at.NAME AS ACTION_NAME
    FROM DB_SOURCE_EPIC_CLARITY.RAW.ORDER_PROC op
    LEFT JOIN DB_SOURCE_EPIC_CLARITY.RAW.ORDER_COMMENT oc ON op.ORDER_PROC_ID = oc.ORDER_ID
    LEFT JOIN DB_SOURCE_EPIC_CLARITY.RAW.ORDER_AUDIT_TRL oa ON op.ORDER_PROC_ID = oa.ORDER_ID
    JOIN DB_SOURCE_EPIC_CLARITY.RAW.CLARITY_EMP emp ON oa.AUDIT_TRL_USER_ID = emp.USER_ID
    JOIN DB_SOURCE_EPIC_CLARITY.RAW.ZC_AUD_TRL_ACTION at ON oa.AUDIT_TRL_ACTION_C = at.AUDIT_TRL_ACTION_C
    WHERE op.ORDER_TYPE_C IN (3, 7, 31, 59, 77)
      AND oc.ORDERING_COMMENT IS NOT NULL
            AND op.ORDER_PROC_ID IN (
          1757499, 1757500, 1757501, 1872943, 1923538,
          1987297, 1987298, 1987299, 1987300, 1987301,
          1987302, 1987303, 2006585
      );

    RETURN 'sp_load_order_comment completed.';
END;
$$;